# Generated by Django 5.2.1 on 2025-07-02 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horarioatencion',
            options={'ordering': ['doctor', 'dia_semana', 'hora_inicio'], 'verbose_name': 'Horario de Atención', 'verbose_name_plural': 'Horarios de Atención'},
        ),
        migrations.AlterUniqueTogether(
            name='horarioatencion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='horarioatencion',
            name='doctor',
            field=models.ForeignKey(default=1, help_text='Doctor al que pertenece este horario de atención.', on_delete=django.db.models.deletion.CASCADE, related_name='horarios_atencion', to='core.doctor', verbose_name='Doctor'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='horarioatencion',
            unique_together={('doctor', 'dia_semana')},
        ),
    ]
