# Generated by Django 5.2.1 on 2025-06-28 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audituser',
            name='accion',
            field=models.CharField(help_text='Tipo de acción realizada (ej: ADICION, MODIFICACION, ELIMINACION)', max_length=50, verbose_name='Acción'),
        ),
        migrations.AlterField(
            model_name='audituser',
            name='registroid',
            field=models.IntegerField(help_text='ID del registro afectado', verbose_name='ID del Registro'),
        ),
        migrations.AlterField(
            model_name='audituser',
            name='usuario',
            field=models.ForeignKey(help_text='Usuario que realizó la acción', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
